version: '3'
services:
  app:
    build:
      context: .
      target: app
    ports:
      - "8080:8080"
    command: ./local/bin/plackup -p 8080 -r -Ilib app.psgi
    volumes:
      - ./lib:/usr/src/app/lib
      - ./t:/usr/src/app/t

