version: '3'
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    command: ./local/bin/plackup -p 8080 -r -Ilib app.psgi
    volumes:
      - ./lib:/usr/src/app/lib

